### ISSUE TITLE
Runing

### ISSUE THREAD

**Issue by Nirvana9808** [blxie/swin-track#1]
I can't find it during run data.tracking. run python main.py SwinTrack Tiny --mixin_config got10k.yaml

**Comment by blxie** [comment]
Firstly, I'm very sorry about that. The solution is as follows.

`${SwinTrack_ROOT}/datasets/easy_builder/builder.py`, comment this line,
https://github.com/blxie/swin-track/blob/f7549d5f4001f6ba108b26ae816a69119b99b5c2/datasets/easy_builder/builder.py#L183

changed code,
```python
    # TRACED datasets settings
    # 在 4 大数据集上进行测试
    config["datasets"] = dataset_config

    # 只使用 GOT-10k 进行测试
    # config["datasets"] = {"GOT10k": {"type": "SOT", "splits": ["val", "test"]}}
    # config["datasets"] = {"GOT10k": {"type": "SOT", "splits": ["test"]}}
    # config["datasets"] = {"TrackingNet": {"type": "SOT", "splits": ["test"]}}
    print(">>>config datasets:", config["datasets"])

    return build_datasets(config, unknown_parameter_handler)
```

The official code maybe more suitable for you, it is more authority.

If it doesnot work for you, maybe you should delete the all cached data in `datasets/cache` additionally.

The final result,
![image](https://user-images.githubusercontent.com/43612290/198506627-2c20b88f-0ddf-4d98-af6d-9b0b3062024d.png)
